import { company } from "@/lib/data";
import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";

export function ExecutiveSummary() {
  return (
    <div className="animate-fade-up rounded-2xl border border-line bg-white p-8 shadow-card sm:p-10">
      <div className="flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-accent" />
        <Badge tone="accent">AI Executive Summary</Badge>
      </div>
      <p className="mt-5 text-2xl font-medium leading-snug tracking-tight text-ink sm:text-3xl">
        “{company.summary}”
      </p>
      <p className="mt-5 text-sm text-ink-muted">
        Generated by EnterpriseCore from company filings, tender feeds, and
        market signals — refreshed continuously.
      </p>
    </div>
  );
}
